"""Minimal, dependency-free HTML rendering shared by manifest/snapshot reports.

No templating engine, no external CSS/JS/fonts/images, no network
fetch, no `<script>` tag anywhere: every report this package renders is
a single self-contained `.html` file (PROJECT_SPEC.md section 23:
"Self-contained... Active JS minimum"). Every user-controlled string
passed through `escape` before it reaches the page, so a source URI, a
license expression, or a warning message can never break out of its
HTML context.
"""

from __future__ import annotations

from collections.abc import Iterable
from html import escape as _escape

_STYLE = """
  :root { color-scheme: light dark; }
  body { font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
         margin: 2rem auto; max-width: 960px; line-height: 1.45; color: #1a1a1a; background: #fff;
         padding: 0 1rem; }
  @media (prefers-color-scheme: dark) { body { color: #e6e6e6; background: #14161a; } }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  h2 { font-size: 1.15rem; margin-top: 2rem; border-bottom: 1px solid #8884;
       padding-bottom: 0.25rem; }
  .meta { color: #666; font-size: 0.9rem; margin-bottom: 1.5rem; }
  @media (prefers-color-scheme: dark) { .meta { color: #aaa; } }
  table { border-collapse: collapse; width: 100%; margin: 0.75rem 0; }
  th, td { text-align: left; padding: 0.35rem 0.6rem; border-bottom: 1px solid #8883;
           font-size: 0.92rem; }
  th { font-weight: 600; }
  code { font-family: ui-monospace, Menlo, Consolas, monospace; font-size: 0.85em;
         word-break: break-all; }
  .status-ok { color: #1a7f37; font-weight: 600; }
  .status-warn { color: #9a6700; font-weight: 600; }
  .status-fail { color: #cf222e; font-weight: 600; }
  .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
               gap: 0.75rem; margin: 0.75rem 0; }
  .stat { border: 1px solid #8883; border-radius: 6px; padding: 0.6rem 0.75rem; }
  .stat .value { font-size: 1.3rem; font-weight: 700; }
  .stat .label { font-size: 0.8rem; color: #666; }
  @media (prefers-color-scheme: dark) { .stat .label { color: #aaa; } }
  footer { margin-top: 2.5rem; font-size: 0.8rem; color: #888; }
"""


def escape(value: object) -> str:
    """Escape ``value`` (stringified first) for safe inclusion in HTML markup."""
    return _escape(str(value), quote=True)


def page(title: str, subtitle: str, body_html: str) -> str:
    """Wrap pre-built section markup in a complete, self-contained HTML document."""
    return (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        f"<title>{escape(title)}</title><style>{_STYLE}</style></head><body>"
        f'<h1>{escape(title)}</h1><p class="meta">{escape(subtitle)}</p>'
        f"{body_html}"
        "<footer>Generated by ragledger report.</footer></body></html>"
    )


def stat_grid(stats: Iterable[tuple[str, object]]) -> str:
    """Render a row of labeled summary numbers."""
    cells = "".join(
        f'<div class="stat"><div class="value">{escape(value)}</div>'
        f'<div class="label">{escape(label)}</div></div>'
        for label, value in stats
    )
    return f'<div class="stat-grid">{cells}</div>'


def table(headers: Iterable[str], rows: Iterable[Iterable[object]]) -> str:
    """Render a simple data table, or a plain "None." paragraph when ``rows`` is empty."""
    row_html = "".join(
        "<tr>" + "".join(f"<td>{escape(cell)}</td>" for cell in row) + "</tr>" for row in rows
    )
    if not row_html:
        return "<p><em>None.</em></p>"
    head_html = "".join(f"<th>{escape(header)}</th>" for header in headers)
    return f"<table><thead><tr>{head_html}</tr></thead><tbody>{row_html}</tbody></table>"
